# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2eb9a47fe702f693b1fd5b466aa7f332f3809a3acb8e83e6cdcbff5f7abb61ffd9a2eda25f247262988815fc73f7ba5ce699b844ae16ae80ad850169d52083af

test:
  secret_key_base: 2f5c0645470eb183b0ceb97de5a5602cf8cee8c41bf2898936fb760aa732aa68d991c14e23550f081773d481c65602dc710a4460e0d924c9f515abdf49addf39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
